image: microsoft/dotnet:latest

stages:
    - build
    - test
    - publish

variables:
    test: "Example.Test"

before_script:
    - "cd src"
    - "dotnet restore"

build:
    stage: build
    script:
        - dotnet build src -c Release
        - mkdir build
        - echo "created build dir"
        - touch build/info.txt
    only:
        - master

test:
    stage: test
    script:
        - echo "testing"
        - "cd $test"
        - "dotnet test"

    only:
        - master

publish:
    stage: publish
    script:
        - dotnet build src -c Release
    only:
        - master
        