image: microsoft/dotnet:latest

stages:
    - build
    - test

variables:
    test: "Example.Test"

before_script:
    - "cd src"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build -p:Version=1.2.3.4"
        - mkdir build
        - echo "created build dir"
        - touch build/info.txt
    artifacts:
      paths:
        - /build/

test:
    stage: test
    script:
        - echo "testing"
        - "cd $test"
        - "dotnet test"
        - test -f "build/info.txt"
