image: microsoft/dotnet:latest

stages:
    - restore
    - build
    - test

variables:
    test: "Example.Test"
    web: "Example.Web"

before_script:
    - "cd src"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script:
        - "cd $test"
        - "dotnet test"